apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: gcr.io/arctic-dynamo-291018/javaproj:1
        ports: 
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: proj1-bd-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: proj1-bd-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: proj1-bd-secret
              key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=arctic-dynamo-291018:us-central1:proj1-bd=tcp:3306"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets/
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: proj1-inst-secret
